//
//  ColorBank.swift
//  whatNext
//
//  Created by HAI DANG on 12/28/17.
//  Copyright © 2017 HAI DANG. All rights reserved.
//

import Foundation
import ChameleonFramework

class ColorBank {
    
    var list = [Color] ()
    
    init() {
        
        list.append(Color(colorFlat: FlatRed(), hex: FlatRed().hexValue(), name: "Red"))
        list.append(Color(colorFlat: FlatOrange(), hex: FlatOrange().hexValue(), name: "Orange"))
        list.append(Color(colorFlat: FlatYellow(), hex: FlatYellow().hexValue(), name: "Yellow"))
        list.append(Color(colorFlat: FlatSand(), hex: FlatSand().hexValue(), name: "Sand"))
        list.append(Color(colorFlat: FlatNavyBlue(), hex: FlatNavyBlue().hexValue(), name: "Navy Blue"))
        list.append(Color(colorFlat: FlatBlack(), hex: FlatBlack().hexValue(), name: "Black"))
        list.append(Color(colorFlat: FlatMagenta(), hex: FlatMagenta().hexValue(), name: "Magenta"))
        list.append(Color(colorFlat: FlatTeal(), hex: FlatTeal().hexValue(), name: "Teal"))
        list.append(Color(colorFlat: FlatSkyBlue(), hex: FlatSkyBlue().hexValue(), name: "Sky Blue"))
        list.append(Color(colorFlat: FlatGreen(), hex: FlatGreen().hexValue(), name: "Green"))
        list.append(Color(colorFlat: FlatMint(), hex: FlatMint().hexValue(), name: "Mint"))
        list.append(Color(colorFlat: FlatWhite(), hex: FlatWhite().hexValue(), name: "White"))
        list.append(Color(colorFlat: FlatGray(), hex: FlatGray().hexValue(), name: "Gray"))
        list.append(Color(colorFlat: FlatForestGreen(), hex: FlatForestGreen().hexValue(), name: "Forest Green"))
        list.append(Color(colorFlat: FlatPurple(), hex: FlatPurple().hexValue(), name: "Purple"))
        list.append(Color(colorFlat: FlatBrown(), hex: FlatBrown().hexValue(), name: "Brown"))
        list.append(Color(colorFlat: FlatPlum(), hex: FlatPlum().hexValue(), name: "Plum"))
        list.append(Color(colorFlat: FlatWatermelon(), hex: FlatWatermelon().hexValue(), name: "Watermelon"))
        list.append(Color(colorFlat: FlatLime(), hex: FlatLime().hexValue(), name: "Lime"))
        list.append(Color(colorFlat: FlatPink(), hex: FlatPink().hexValue(), name: "Pink"))
        list.append(Color(colorFlat: FlatMaroon(), hex: FlatMaroon().hexValue(), name: "Maroon"))
        list.append(Color(colorFlat: FlatCoffee(), hex: FlatCoffee().hexValue(), name: "Coffe"))
        list.append(Color(colorFlat: FlatPowderBlue(), hex: FlatPowderBlue().hexValue(), name: "Powder Blue"))
        list.append(Color(colorFlat: FlatBlue(), hex: FlatBlue().hexValue(), name: "Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFB6C1")!,hex: "#FFB6C1", name: "Light Pink"))
        list.append(Color(colorFlat: UIColor(hexString: "#F0F8FF")!,hex: "#F0F8FF", name: "Alice Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#FAEBD7")!,hex: "#FAEBD7", name: "Antique White"))
        list.append(Color(colorFlat: UIColor(hexString: "#00FFFF")!,hex: "#00FFFF", name: "Aqua"))
        list.append(Color(colorFlat: UIColor(hexString: "#7FFFD4")!,hex: "#7FFFD4", name: "Aquamarine"))
        list.append(Color(colorFlat: UIColor(hexString: "#F0FFFF")!,hex: "#F0FFFF", name: "Azure"))
        list.append(Color(colorFlat: UIColor(hexString: "#F5F5DC")!,hex: "#F5F5DC", name: "Beige"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFE4C4")!,hex: "#FFE4C4", name: "Bisque"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFEBCD")!,hex: "#FFEBCD", name: "Blanched Almond"))
        list.append(Color(colorFlat: UIColor(hexString: "#8A2BE2")!,hex: "#8A2BE2", name: "BlueViolet"))
        list.append(Color(colorFlat: UIColor(hexString: "#DEB887")!,hex: "#DEB887", name: "Burly Wood"))
        list.append(Color(colorFlat: UIColor(hexString: "#5F9EA0")!,hex: "#5F9EA0", name: "Cadet Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#7FFF00")!,hex: "#7FFF00", name: "Chartreuse"))
        list.append(Color(colorFlat: UIColor(hexString: "#D2691E")!,hex: "#D2691E", name: "Chocolate"))
        list.append(Color(colorFlat: UIColor(hexString: "#FF7F50")!,hex: "#FF7F50", name: "Coral"))
        list.append(Color(colorFlat: UIColor(hexString: "#6495ED")!,hex: "#6495ED", name: "Cornflower Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#DC143C")!,hex: "#DC143C", name: "Crimson"))
        list.append(Color(colorFlat: UIColor(hexString: "#00FFFF")!,hex: "#00FFFF", name: "Cyan"))
        list.append(Color(colorFlat: UIColor(hexString: "#00008B")!,hex: "#00008B", name: "Dark Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#008B8B")!,hex: "#008B8B", name: "Dark Cyan"))
        list.append(Color(colorFlat: UIColor(hexString: "#B8860B")!,hex: "#B8860B", name: "Dark Golden Rod"))
        list.append(Color(colorFlat: UIColor(hexString: "#A9A9A9")!,hex: "#A9A9A9", name: "Dark Gray"))
        list.append(Color(colorFlat: UIColor(hexString: "#BDB76B")!,hex: "#BDB76B", name: "Dark Khaki"))
        list.append(Color(colorFlat: UIColor(hexString: "#8B008B")!,hex: "#8B008B", name: "Dark Magenta"))
        list.append(Color(colorFlat: UIColor(hexString: "#556B2F")!,hex: "#556B2F", name: "Dark Olive Green "))
        list.append(Color(colorFlat: UIColor(hexString: "#FF8C00")!,hex: "#FF8C00", name: "Dark Orange"))
        list.append(Color(colorFlat: UIColor(hexString: "#9932CC")!,hex: "#9932CC", name: "Dark Orchid"))
        list.append(Color(colorFlat: UIColor(hexString: "#8B0000")!,hex: "#8B0000", name: "Dark Red"))
        list.append(Color(colorFlat: UIColor(hexString: "#E9967A")!,hex: "#E9967A", name: "Dark Salmon"))
        list.append(Color(colorFlat: UIColor(hexString: "#8FBC8F")!,hex: "#8FBC8F", name: "Dark Sea Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#483D8B")!,hex: "#483D8B", name: "Dark Slate Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#2F4F4F")!,hex: "#2F4F4F", name: "Dark Slate Gray"))
        list.append(Color(colorFlat: UIColor(hexString: "#00CED1")!,hex: "#00CED1", name: "Dark Turquoise"))
        list.append(Color(colorFlat: UIColor(hexString: "#9400D3")!,hex: "#9400D3", name: "DarkViolet"))
        list.append(Color(colorFlat: UIColor(hexString: "#FF1493")!,hex: "#FF1493", name: "Deep Pink"))
        list.append(Color(colorFlat: UIColor(hexString: "#00BFFF")!,hex: "#00BFFF", name: "Deep Sky Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#696969")!,hex: "#696969", name: "Dim Gray"))
        list.append(Color(colorFlat: UIColor(hexString: "#1E90FF")!,hex: "#1E90FF", name: "Dodger Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#B22222")!,hex: "#B22222", name: "Fire Brick"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFFAF0")!,hex: "#FFFAF0", name: "Floral White"))
        list.append(Color(colorFlat: UIColor(hexString: "#FF00FF")!,hex: "#FF00FF", name: "Fuchsia"))
        list.append(Color(colorFlat: UIColor(hexString: "#DCDCDC")!,hex: "#DCDCDC", name: "Gainsboro"))
        list.append(Color(colorFlat: UIColor(hexString: "#F8F8FF")!,hex: "#F8F8FF", name: "GhostWhite"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFD700")!,hex: "#FFD700", name: "Gold"))
        list.append(Color(colorFlat: UIColor(hexString: "#DAA520")!,hex: "#DAA520", name: "Golden Rod"))
        list.append(Color(colorFlat: UIColor(hexString: "#ADFF2F")!,hex: "#ADFF2F", name: "GreenYellow"))
        list.append(Color(colorFlat: UIColor(hexString: "#F0FFF0")!,hex: "#F0FFF0", name: "Honey Dew"))
        list.append(Color(colorFlat: UIColor(hexString: "#FF69B4")!,hex: "#FF69B4", name: "Hot Pink"))
        list.append(Color(colorFlat: UIColor(hexString: "#CD5C5C")!,hex: "#CD5C5C", name: "Indian Red"))
        list.append(Color(colorFlat: UIColor(hexString: "#4B0082")!,hex: "#4B0082", name: "Indigo"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFFFF0")!,hex: "#FFFFF0", name: "Ivory"))
        list.append(Color(colorFlat: UIColor(hexString: "#F0E68C")!,hex: "#F0E68C", name: "Khaki"))
        list.append(Color(colorFlat: UIColor(hexString: "#E6E6FA")!,hex: "#E6E6FA", name: "Lavender"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFF0F5")!,hex: "#FFF0F5", name: "Lavender Blush"))
        list.append(Color(colorFlat: UIColor(hexString: "#7CFC00")!,hex: "#7CFC00", name: "Lawn Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFFACD")!,hex: "#FFFACD", name: "Lemon Chiffon"))
        list.append(Color(colorFlat: UIColor(hexString: "#ADD8E6")!,hex: "#ADD8E6", name: "Light Blue "))
        list.append(Color(colorFlat: UIColor(hexString: "#F08080")!,hex: "#F08080", name: "Light Coral"))
        list.append(Color(colorFlat: UIColor(hexString: "#E0FFFF")!,hex: "#E0FFFF", name: "Light Cyan"))
        list.append(Color(colorFlat: UIColor(hexString: "#FAFAD2")!,hex: "#FAFAD2", name: "Light Golden Rod Yellow"))
        list.append(Color(colorFlat: UIColor(hexString: "#90EE90")!,hex: "#90EE90", name: "Light Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFB6C1")!,hex: "#FFB6C1", name: "Light Pink"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFA07A")!,hex: "#FFA07A", name: "Light Salmon"))
        list.append(Color(colorFlat: UIColor(hexString: "#20B2AA")!,hex: "#20B2AA", name: "Light Sea Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#778899")!,hex: "#778899", name: "Light Slate Gray"))
        list.append(Color(colorFlat: UIColor(hexString: "#B0C4DE")!,hex: "#B0C4DE", name: "Light Steel Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFFFE0")!,hex: "#FFFFE0", name: "Light Yellow"))
        list.append(Color(colorFlat: UIColor(hexString: "#FAF0E6")!,hex: "#FAF0E6", name: "Linen"))
        list.append(Color(colorFlat: UIColor(hexString: "#66CDAA")!,hex: "#66CDAA", name: "Medium AquaMarine"))
        list.append(Color(colorFlat: UIColor(hexString: "#BA55D3")!,hex: "#BA55D3", name: "Medium Orchid"))
        list.append(Color(colorFlat: UIColor(hexString: "#9370DB")!,hex: "#9370DB", name: "Medium Purple"))
        list.append(Color(colorFlat: UIColor(hexString: "#3CB371")!,hex: "#3CB371", name: "Medium Sea Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#7B68EE")!,hex: "#7B68EE", name: "Medium Slate Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#00FA9A")!,hex: "#00FA9A", name: "Medium Spring Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#48D1CC")!,hex: "#48D1CC", name: "Medium Turquoise"))
        list.append(Color(colorFlat: UIColor(hexString: "#C71585")!,hex: "#C71585", name: "Medium Violet Red"))
        list.append(Color(colorFlat: UIColor(hexString: "#191970")!,hex: "#191970", name: "Midnight Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#F5FFFA")!,hex: "#F5FFFA", name: "Mint Cream"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFE4E1")!,hex: "#FFE4E1", name: "Misty Rose"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFE4B5")!,hex: "#FFE4B5", name: "Moccasin"))
        list.append(Color(colorFlat: UIColor(hexString: "#FDF5E6")!,hex: "#FDF5E6", name: "Old Lace"))
        list.append(Color(colorFlat: UIColor(hexString: "#808000")!,hex: "#808000", name: "Olive"))
        list.append(Color(colorFlat: UIColor(hexString: "#6B8E23")!,hex: "#6B8E23", name: "Olive Drab"))
        list.append(Color(colorFlat: UIColor(hexString: "#FF4500")!,hex: "#FF4500", name: "Orange Red"))
        list.append(Color(colorFlat: UIColor(hexString: "#DA70D6")!,hex: "#DA70D6", name: "Orchid"))
        list.append(Color(colorFlat: UIColor(hexString: "#EEE8AA")!,hex: "#EEE8AA", name: "Pale Golden Rod"))
        list.append(Color(colorFlat: UIColor(hexString: "#98FB98")!,hex: "#98FB98", name: "Pale Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#AFEEEE")!,hex: "#AFEEEE", name: "Pale Turquoise"))
        list.append(Color(colorFlat: UIColor(hexString: "#DB7093")!,hex: "#DB7093", name: "Pale Violet Red"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFEFD5")!,hex: "#FFEFD5", name: "Papaya Whip"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFDAB9")!,hex: "#FFDAB9", name: "Peach Puff"))
        list.append(Color(colorFlat: UIColor(hexString: "#CD853F")!,hex: "#CD853F", name: "Peru"))
        list.append(Color(colorFlat: UIColor(hexString: "#663399")!,hex: "#663399", name: "Rebecca Purple"))
        list.append(Color(colorFlat: UIColor(hexString: "#BC8F8F")!,hex: "#BC8F8F", name: "Rosy Brown"))
        list.append(Color(colorFlat: UIColor(hexString: "#4169E1")!,hex: "#4169E1", name: "Royal Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#FA8072")!,hex: "#FA8072", name: "Salmon"))
        list.append(Color(colorFlat: UIColor(hexString: "#F4A460")!,hex: "#F4A460", name: "Sandy Brown"))
        list.append(Color(colorFlat: UIColor(hexString: "#2E8B57")!,hex: "#2E8B57", name: "Sea Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFF5EE")!,hex: "#FFF5EE", name: "Sea Shell"))
        list.append(Color(colorFlat: UIColor(hexString: "#A0522D")!,hex: "#A0522D", name: "Sienna"))
        list.append(Color(colorFlat: UIColor(hexString: "#C0C0C0")!,hex: "#C0C0C0", name: "Silver"))
        list.append(Color(colorFlat: UIColor(hexString: "#6A5ACD")!,hex: "#6A5ACD", name: "Slate Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#708090")!,hex: "#708090", name: "Slate Gray"))
        list.append(Color(colorFlat: UIColor(hexString: "#FFFAFA")!,hex: "#FFFAFA", name: "Snow"))
        list.append(Color(colorFlat: UIColor(hexString: "#00FF7F")!,hex: "#00FF7F", name: "Spring Green"))
        list.append(Color(colorFlat: UIColor(hexString: "#4682B4")!,hex: "#4682B4", name: "Steel Blue"))
        list.append(Color(colorFlat: UIColor(hexString: "#D2B48C")!,hex: "#D2B48C", name: "Tan"))
        list.append(Color(colorFlat: UIColor(hexString: "#D8BFD8")!,hex: "#D8BFD8", name: "Thistle"))
        list.append(Color(colorFlat: UIColor(hexString: "#FF6347")!,hex: "#FF6347", name: "Tomato"))
        list.append(Color(colorFlat: UIColor(hexString: "#40E0D0")!,hex: "#40E0D0", name: "Turquoise"))
        list.append(Color(colorFlat: UIColor(hexString: "#EE82EE")!,hex: "#EE82EE", name: "Violet"))
        list.append(Color(colorFlat: UIColor(hexString: "#F5DEB3")!,hex: "#F5DEB3", name: "Wheat"))
        list.append(Color(colorFlat: UIColor(hexString: "#F5F5F5")!,hex: "#F5F5F5", name: "White Smoke"))
        list.append(Color(colorFlat: UIColor(hexString: "#9ACD32")!,hex: "#9ACD32", name: "Yellow Green"))
      
    }
    
}
